# Generated by Django 6.0.5 on 2026-07-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_categories',
            field=models.ManyToManyField(blank=True, related_name='eligible_coupons', to='products.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_products',
            field=models.ManyToManyField(blank=True, related_name='eligible_coupons', to='products.product'),
        ),
    ]
